### ISSUE TITLE
Upside down explanation to Leave-one-out cross-validation in section 3.4.6

### ISSUE THREAD

**Issue by shinhongwu** [topepo/FES#38]
>Leave-one-out cross-validation would have very low bias since its analysis set is only one sample apart from the training set.

I though "Leave-one-out cross-validation" should have very "high" bias instead of "low" bias.   Am I wrong or is it a typo?

**Comment by topepo** [comment]
The bias increases as the amount of data held out in the assessment set increases. That's why the bootstrap (with leaves out about 36% out on average) has such a bad bias problem. 

[Section 10 of this paper](https://people.eecs.berkeley.edu/~jordan/sail/readings/archive/efron-improve_cv.pdf) summarizes it well (where "cross-validation" in this quote is LOO): 

![image](https://user-images.githubusercontent.com/5731043/45419812-525bf100-b656-11e8-8206-2c9a5cfcdec1.png)

It's more complicated that this on the variance side IMO but pretty clear about the bias.
