### ISSUE TITLE
Topic suggestion within missing data

### ISSUE THREAD

**Issue by mlduarte** [topepo/FES#73]
In Chapter 8: Handling Missing Data, would you be able to elaborate on dealing with data that doesn't make sense for a subset of the "population".  For example, with respect to the full Ames data available on  [Kaggle](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data), there are a number of features relevant only to houses with a garage (such as GarageYrBlt, GarageCars, GarageArea, GarageQual, GarageCond) and a number of features relevant only to houses with a Basement, etc.

How is the missingness of garage information referred to for houses without garages? MNAR or is there another term?  Are there suggestions for putting in dummy values for numerical features, e.g. for GarageYrBuild with values in such as 2006, does it make a difference to use the median vs a 0 for different types of models?  What other types of suggestions exist specific to this type of missing data?

A discussion of other methods and their pros/cons, such as Indicator variables for missingness of continuous variables (in a general sense and in relation to the sometimes irrelevant features discussed above) as per notes by [Andrew Gelman](http://www.stat.columbia.edu/~gelman/arm/missing.pdf) could also be helpful to make this a complete topic on data missingness.

**Comment by kjell-stattenacity** [comment]
Thanks for your questions and suggestions.  With respect to the Ames data, we did not address every possible issue of missingness.  Instead, we highlighted some examples and how to address these (like Alley).  Ideally, the principles presented in the text can be generalized to other predictors (like houses with garages).  Houses without garages could be due to the type of building (which would not be random), or possibly due to an omission in the original data (which could be random).

We have completed the text and are nearly finished with the copy editing, so there won't be any additions at this time.  But we will keep in mind your suggestions for the second edition.  :>

**Comment by mlduarte** [comment]
Thanks for the response; good point about the absence/presence of a garage being related to the type of building, however, in the above I had been referring to how to treat the other features explaining the garage (i.e., year built, size, etc) for buildings without a garage. I.e those with garage presence = false will have the same dummy value for other features explaining  the characteristics of the garage (year garage built, garage size, etc).   It seems misleading (to me) to refer to these features as missing for those houses without a garage.  Anyway, hopefully something that can be elaborated on in the following edition.

I look forward to the book coming out!
